### ISSUE TITLE
IWS Presentation

### ISSUE THREAD

**Issue by awarehouse** [awarehouse/thenam#10]
## Task List
- [ ] Post Meeting Notes
- [ ] Follow up email to clients w/ next steps

## Next Steps (THIS WOULD BE CRAFTED BY THE STRATEGY TEAM, THEN THE PM WOULD UPDATE THE STRATEGY BRIEF TICKET WITH THE NECESSARY TASKS) 
- [ ] Areas to research further
