### ISSUE TITLE
Site Audit

### ISSUE THREAD

**Issue by awarehouse** [awarehouse/thenam#11]
## Tasks
- [ ] Pull Page Rank
- [ ] Pull SEO & Keywords

## Next Steps
- [ ] Create slides based on findings
...
