### ISSUE TITLE
User Journey Exercise

### ISSUE THREAD

**Issue by awarehouse** [awarehouse/thenam#12]
## Tasks
- [ ] Review Clients answers to the User Journey Exercises
- [ ] Run any additional personas through the user journey Exercise

## Next Steps
- [ ] Summarize User Journey Exercise to use for Site Map & Strategy Brief
